
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author 胡維仁
 */
public class game1 extends JFrame {
    control button1=new control();
    control button2=new control();
    control button3=new control();
    control button4=new control();
    control button5=new control();
    control button6=new control();
    control button7=new control();
    control button8=new control();
    control button9=new control();
    public  static int count=0;
    /**
     * Creates new form game1
     */
    public game1() {
        if(count==0){
        initComponents();
        add(button1);
        add(button2);
        add(button3);
        add(button4);
        add(button5);
        add(button6);
        add(button7);
        add(button8);
        add(button9);
        setLayout(new GridLayout(3, 3));
        setBounds(0, 0, 3000, 3000);
        setVisible(true);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        }
        else{
        
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        setLayout(null);
    }// </editor-fold>
    protected int index=1;


    class control extends JButton implements ActionListener{
        public control(){
            this.addActionListener(this);
        }
        @Override
        public void actionPerformed(ActionEvent e) {
            if (this.getText().equals("")) {
                if (index % 2 == 0) {
                    this.setText("O");
                } else {
                    this.setText("X");
                }
            }
            else{
                // this.setText("P");
            }
            int a=0;
            if(button1.getText()==button2.getText()&&button2.getText()==button3.getText()&&button1.getText()!=""){
                a=1;
            }
            else  if(button4.getText()==button5.getText()&&button5.getText()==button6.getText()&&button4.getText()!=""){

                a=1;
            }
            else  if(button7.getText()==button8.getText()&&button8.getText()==button9.getText()&&button7.getText()!=""){
                a=1;
            }
            else if(button1.getText()==button4.getText()&&button4.getText()==button7.getText()&&button1.getText()!=""){

                a=1;
            }
            else if(button2.getText()==button5.getText()&&button5.getText()==button8.getText()&&button2.getText()!=""){

                a=1;
            }
            else  if(button3.getText()==button6.getText()&&button6.getText()==button9.getText()&&button3.getText()!=""){

                a=1;
            }
            else if(button1.getText()==button5.getText()&&button5.getText()==button9.getText()&&button1.getText()!=""){

                a=1;
            }
            else if(button3.getText()==button5.getText()&&button5.getText()==button7.getText()&&button3.getText()!=""){

                a=1;
            }
            else{
                if(index==9){
                    System.out.println("平手");
                }
            }
            if(a==1){

                button1.setText("");
                button2.setText("");
                button3.setText("");
                button4.setText("");
                button5.setText("");
                button6.setText("");
                button7.setText("");
                button8.setText("");
                button9.setText("");
                winloss();
            }
            index++;
        }
    }
    public void winloss(){
        JOptionPane.showMessageDialog(null, "繼續遊戲", "恭喜獲勝",JOptionPane.WARNING_MESSAGE);
         count++;
         move m=new move();
       
       
    }
    
    // Variables declaration - do not modify
    // End of variables declaration
}

